### ISSUE TITLE
Error exporting with Passwords

### ISSUE THREAD

**Issue by LostInTexas** [fordnn/usersexportimport#16]
We're doing a long overdue upgrade to our DNN site and installed the most current forDNN.usersexportimport module, works great except when we try to export the users with their password.
DNN is 9.12.0
Windows Server 2022 21H2
It is a VM

Detail of the error:
AbsoluteURL:/API/forDNN.UsersExportImport/ExportImport/DoExport

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:bf6aeaab-bb89-4856-82bf-0845766dfa1d

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

RawUrl:

Referrer:

UserAgent:

ExceptionHash:mRbR1BMJ6pmcgdk1zehDEiIlMIc=

Message:Object reference not set to an instance of an object.

StackTrace:

   at DotNetNuke.Security.Membership.AspNetMembershipProvider.GetPassword(UserInfo user, String passwordAnswer)
   at DotNetNuke.Entities.Users.UserController.GetPassword(UserInfo& user, String passwordAnswer)
   at forDNN.Modules.UsersExportImport.Controller.ExportController.AddPasswordsColumn(Int32 PortalId, DataTable dt)
   at forDNN.Modules.UsersExportImport.Controller.ExportController.DoExport(Int32 PortalId, ExportInfo objExportInfo)
InnerMessage:

InnerStackTrace:

Source:DotNetNuke

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

**Comment by fordnn** [comment]
Wasn't able to reproduce this issue on clear DNN 9.12.0 installation. May you contact support [at] fordnn com to provide a bit more details? Thanks in advance!
